version: '0.1.0'

services:
  shorturl:
    build: ./shorturl
    container_name: shorturl
    depends_on:
      - postgresql-shorturl
    ports:
      - "8888:9000"

  postgresql-shorturl:
    build: ./postgresql
    restart: always
    container_name: postgresql-shorturl
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app 
      PGPASSWORD: app
      POSTGRES_DB: shorturl
      POSTGRES_HOST_AUTH_METHOD: trust

