version: '0.1'

services:

  shorturl:
    build: .
    container_name: shorturl
    hostname: shorturl
    ports:
      - "8888:9000"


  postgresql-shorturl:
    image: postgres
    restart: always
    container_name: postgresql-shorturl
    hostname: postgresql-shorturl
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app 
      POSTGRES_DB: shorturl


  networks:
    shorturl:
      external: true

